- name: Install zsh
  homebrew:
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
    state: present

- name: Set default shell to installed zsh
  become: yes
  user: name={{ansible_user_id}} shell=/usr/local/bin/zsh

- name: Clone oh-my-zsh repo
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh

- name: Remove standard .zshrc
  file: path=~/.zshrc state=absent

- name: Deploy .zshrc
  template: src=../../../../../misc/zsh/zshrc dest=~/.zshrc

- name: Source .zshrc
  command: source ~/.zshrc

#- name: Install zsh plugins => zsh-completions
#  command: git clone https://github.com/zsh-users/zsh-completions ~/.oh-my-zsh/custom/plugins/zsh-completions
#
#- name: Install zsh plugins => zsh-syntax-highlighting
#  command: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
