- name: Install zsh
  homebrew:
    name:
      - zsh
    state: present

- name: Install oh-my-zsh
  command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  become: yes

- name: Set default shell to installed zsh
  become: yes
  user: name={{ansible_user_id}} shell=/usr/local/bin/zsh

- name: Install zsh plugins => zsh-completions
  command: git clone https://github.com/zsh-users/zsh-completions ~/.oh-my-zsh/custom/plugins/zsh-completions

- name: Install zsh plugins => zsh-syntax-highlighting
  command: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
