- name: Add Cask tap
  homebrew_tap: tap=homebrew/cask-fonts state=present
  tags:
    - cask

- name: Install Cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  tags:
    - cask
  ignore_errors: yes
  with_items:
    - 1password
    - alfred
    - android-file-transfer
    - arq
    - bartender
    - bettertouchtool
    - bitbar
    - ccleaner
    - chromedriver
    - cyberduck
    - default-folder-x
    - dash
    - disk-inventory-x
    - docker
    - dropbox
    - evernote
    - firefoxdeveloperedition
    - flux
    - font-firacode-nerd-font
    - google-chrome
    - growlnotify
    - iterm2
    - xquartz
    - hammerspoon
    - hazel
    - istat-menus
    - karabiner
    - keyboard-maestro
    - ngrok
    - omnifocus
    - postgres
    - rescuetime
    - sequel-pro
    - shortcat
    - slack
    - mattr-slate
    - sourcetree
    - spotify
    - startupizer
    - synergy
    - teamviewer
    - telegram
    - the-unarchiver
    - time-out
    - trickster
    - visual-studio-code-insiders
    - whatpulse
    - xld
