- name: Install Homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  tags:
    - homebrew
  with_items:
    - chromedriver
    - dfu-programmer
    - dfu-util
    - diff-so-fancy
    - elasticsearch
    - elixir
    - exercism
    - git
    - git-flow
    - hub
    - imagemagick
    - mas
    - phantomjs
    - rbenv
    - reattach-to-user-namespace
    - redis
    - ruby-build
    - tmux
    - vim
    - yarn
