- name: Add Homebrew Taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - crisidev/homebrew-chunkwm

- name: Install Homebrew packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  tags:
    - homebrew

- name: Remove Homebrew packages
  tags:
    - homebrew
  homebrew:
    name:
      - rbenv
    state: absent
