- name: Add Homebrew Taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - crisidev/homebrew-chunkwm

- name: Install Homebrew packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  tags:
    - homebrew
  with_items:
    - asdf
    - awsebcli
    - chunkwm
    - dfu-programmer
    - dfu-util
    - diff-so-fancy
    - elasticsearch@2.4
    - { name: emacs, options: "with-cocoa,with-gnutls" }
    - entr
    - exercism
    - fzy
    - git
    - git-flow
    - hub
    - imagemagick
    - koekeishiya/formulae/skhd
    - mas
    - most
    - multitail
    - reattach-to-user-namespace
    - redis
    - ruby-build
    - terminal-notifier
    - tldr
    - tmux
    - nvim
    - yarn
    - yqrashawn/goku/goku

- name: Remove Homebrew packages
  tags:
    - homebrew
  homebrew:
    name:
      - rbenv
    state: absent
