- name: Link dotfiles
  command: cp -r {{ playbook_dir }}/misc ~/.dotfiles

- name: Link zshrc
  file:
    src: ~/.dotfiles/zsh/zshrc
    path: ~/.zshrc
    state: link
    force: yes

- name: Link vimrc
  file:
    src: ~/.dotfiles/vimrc
    path: ~/.vimrc
    state: link
    force: yes

- name: Link gitconfig
  file:
    src: ~/.dotfiles/git/gitconfig
    path: ~/.gitconfig
    state: link
    force: yes

- name: Link gitignore_global
  file:
    src: ~/.dotfiles/git/gitignore_global
    path: ~/.gitignore_global
    state: link
    force: yes

- name: Link gemrc
  file:
    src: ~/.dotfiles/ruby/gemrc
    path: ~/.gemrc
    state: link
    force: yes

- name: Link hyper.js
  file:
    src: ~/.dotfiles/hyper.js
    path: ~/.hyper.js
    state: link
    force: yes
