- name: Link dotfiles
  file:
    src: "{{ playbook_dir | dirname }}"
    path: ~/.dotfiles
    state: link
    force: yes

- name: Link zshrc
  file:
    src: ~/.dotfiles/zsh/zshrc
    path: ~/.zshrc
    state: link
    force: yes

- name: Link tmux.conf
  file:
    src: ~/.dotfiles/etc/tmux/.tmux.conf
    path: ~/.tmux.conf
    state: link
    force: yes

- name: Link tmux.conf.local
  file:
    src: ~/.dotfiles/etc/tmux/.tmux.conf.local
    path: ~/.tmux.conf.local
    state: link
    force: yes

- name: Link mackup.cfg
  file:
    src: ~/.dotfiles/etc/mackup.cfg
    path: ~/.mackup.cfg
    state: link
    force: yes

- name: Link asdfrc
  file:
    src: ~/.dotfiles/etc/asdfrc
    path: ~/.asdfrc
    state: link
    force: yes

- name: Link gitignore_global
  file:
    src: ~/.dotfiles/etc/gitignore_global
    path: ~/.gitignore_global
    state: link
    force: yes

- name: Link chunkwmrc
  file:
    src: ~/.dotfiles/etc/chunkwmrc
    path: ~/.chunkwmrc
    state: link
    force: yes

- name: Link skhdrc
  file:
    src: ~/.dotfiles/etc/skhdrc
    path: ~/.skhdrc
    state: link
    force: yes

- name: Link karabiner.edn
  file:
    src: ~/.dotfiles/etc/karabiner.edn
    path: ~/.config/karabiner.edn
    state: link
    force: yes
