- name: Copy misc to .dotfiles
  copy:
    src: dotfiles/
    dest: ~/.dotfiles
    force: yes

- name: Link gitconfig
  file:
    src: ~/.dotfiles/git/gitconfig
    path: ~/.gitconfig
    state: link
    force: yes

- name: Link gitignore_global
  file:
    src: ~/.dotfiles/git/gitignore_global
    path: ~/.gitignore_global
    state: link
    force: yes

- name: Link gemrc
  file:
    src: ~/.dotfiles/ruby/gemrc
    path: ~/.gemrc
    state: link
    force: yes

- name: Link zprofile
  file:
    src: ~/.dotfiles/shell/zprofile
    path: ~/.zprofile
    state: link
    force: yes

- name: Link zshrc
  file:
    src: ~/.dotfiles/shell/zshrc
    path: ~/.zshrc
    state: link
    force: yes
