- name: Link dotfiles
  file:
    src: "{{ playbook_dir | dirname }}"
    path: ~/.dotfiles
    state: link
    force: yes

- name: Link zshrc
  file:
    src: ~/.dotfiles/zsh/zshrc
    path: ~/.zshrc
    state: link
    force: yes

- name: Link slate
  file:
    src: ~/.dotfiles/etc/slate
    path: ~/.slate
    state: link
    force: yes

- name: Link tmux.conf
  file:
    src: ~/.dotfiles/etc/tmux.conf
    path: ~/.tmux.conf
    state: link
    force: yes
