- name: Link dotfiles
  file:
    src: "{{ playbook_dir | dirname }}"
    path: ~/.dotfiles
    state: link
    force: yes

- name: Link zshrc
  file:
    src: ~/.dotfiles/zsh/zshrc
    path: ~/.zshrc
    state: link
    force: yes
