- name: Clone keyboard
  git:
    repo: https://github.com/narze/keyboard
    dest: "{{ playbook_dir | dirname }}/etc/keyboard"

- name: Link Hammerspoon config
  file:
    src: "{{ playbook_dir | dirname }}/etc/keyboard/hammerspoon"
    path: ~/.hammerspoon/keyboard
    state: link
    force: yes

- name: Ensure require keyboard script
  lineinfile:
    path: ~/.hammerspoon/init.lua
    line: require('keyboard')
