- name: Add Homebrew Taps
  homebrew_tap:
    tap: heroku/brew
    state: present

- name: Install Heroku
  homebrew:
    name: heroku
    state: present
  tags:
    - heroku

- name: Install heroku plugins
  command: heroku plugins:install heroku-accounts
  tags:
    - heroku-plugins
