---
- name: Install node.js (Dubnium LTS) via nvm
  shell: . $(brew list nvm | ack 'nvm.sh') && nvm install --lts='Dubnium'

- name: Ensure nvm use installed node.js
  shell: . $(brew list nvm | ack 'nvm.sh') && nvm use default

- name: Install yarn
  homebrew:
    name: yarn
    state: present

- name: Uninstall node dependencies
  command: brew uninstall --ignore-dependencies node
  ignore_errors: yes

- name: link node to brew (Cellar)
  file:
    src: ~/.nvm/versions/node/
    dest: /usr/local/Cellar/node
    state: link
    force: yes
