---
- name: Ensure nvm installed.
  homebrew: name=nvm state=present

- name: Ensure nvm directory created.
  file:
    path: ~/.nvm
    state: directory

- name: Install node.js (Dubnium LTS) via nvm
  shell: . $(brew list nvm | ack 'nvm.sh') && nvm install --lts='Dubnium'

- name: Ensure nvm use installed node.js
  shell: . $(brew list nvm | ack 'nvm.sh') && nvm use default

- name: Install yarn
  homebrew:
    name: yarn
    state: present

- name: Uninstall node dependencies
  command: brew uninstall --ignore-dependencies node

- name: link node to brew (Cellar)
    file:
      path: /usr/local/Cellar/
      src: ~/.nvm/versions/node/
      state: link
      force: yes