---
- name: Ensure rbenv installed.
  homebrew: name=rbenv state=present

- name: Ensure ruby-build installed.
  homebrew: name=ruby-build state=present

- name: Ensure nvm installed.
  homebrew: name=nvm state=present

- name: Ensure nvm directory created.
  file:
    path: ~/.nvm
    state: directory

- name: source .bash_profile
  become: no
  shell: source ~/.bash_profile
  args:
    executable: /bin/bash
