---

- name: Ensure nvm installed.
  homebrew: name=nvm state=present

- name: Ensure nvm directory created.
  file:
    path: ~/.nvm
    state: directory

- name: Ensure rbenv installed.
  homebrew: name=rbenv state=present
  register: rbenv_installed

- name: Ensure ruby-build installed.
  homebrew: name=ruby-build state=present

- name: Show rbenv_installed output
  debug:
    msg: '{{rbenv_installed}}'

- name : source .zshrc
  shell: source ~/.zshrc
  args:
    executable: /usr/local/bin/zsh
  register: sourced
  when : rbenv_installed | success
  become: no

- name: Show sourced output
  debug:
    msg: '{{sourced}}'
