---
- name: Ensure rbenv installed.
  homebrew: name=rbenv state=present
  register: rbenv_installed

- name: Ensure ruby-build installed.
  homebrew: name=ruby-build state=present

- name: Install ruby 2.4.1
  command: rbenv install 2.4.1
  ignore_errors: yes

- name: Global ruby 2.4.1
  command: rbenv global 2.4.1

- name: rbenv Rehash
  command: rbenv rehash

- name: Install Rails 5.1.4
  command: gem install rails -v 5.1.4 --no-ri --no-doc
  ignore_errors: yes

- name: rbenv Rehash
  command: rbenv rehash
