- name: Install Homebrew packages
  homebrew:
    name:
      - ack
      - asciinema
      - asciiquarium
      - cowsay
      - curl
      - figlet
      = fortune
      - git
      - heroku
      - mas
      - nginx
      - nvm
      - postgresql
      - rbenv
      - redis
      - ruby-build
      - sl
      - sqlite
      - tree
      - wget
      - zsh
    state: present
  tags:
    - homebrew
  with_items:

