- name: Install Homebrew packages
  tags:
    - homebrew
  homebrew:
    name:
      - ack
      - asciinema
      - asciiquarium
      - cowsay
      - curl
      - figlet
      - fortune
      - git
      - mas
      - nginx
      - nvm
      - postgresql
      - rbenv
      - redis
      - ruby-build
      - sl
      - sqlite
      - tree
      - wget
    state: present
