- name: Install Homebrew packages
  tags:
    - homebrew
  command: brew install "{{ item }}"
  with_items:
    - ack
    - curl
    - git
    - git-flow
    - postgresql
    - pyenv
    - redis
    - sqlite
    - thefuck
    - tree
    - wget

