- name: Install Homebrew Cask packages
  tags:
    - cask
  command: brew cask install "{{ item }}"
  with_items:
    - 1password
    - discord
    - google-backup-and-sync
    - google-chrome
    - jetbrains-toolbox
    - slack
    - spotify
    - visual-studio-code
  ignore_errors: yes
